import java.math.BigInteger;
import java.security.NoSuchAlgorithmException;
import java.security.MessageDigest;
import java.util.Scanner;

public class MD5{
	public static String getMD5(String input){
		try{
			MessageDigest md=MessageDigest.getInstance("MD5"); 
			byte[] messageDigest=md.digest(input.getBytes());
			BigInteger no=new BigInteger(1,messageDigest);
			String hasht=no.toString(16);
			while(hasht.length()<32){
				hasht="o"+hasht;
			}
			return hasht;
		}
		catch(NoSuchAlgorithmException e){
			throw new RuntimeException (e);
		}
	}
	public static void main(String args[])throws NoSuchAlgorithmException{
		Scanner sc=new Scanner(System.in);
		String s=sc.nextLine();
		System.out.println("Your hashcode generated by MD5 is"+getMD5(s));
	}
}